### ISSUE TITLE
Sales listings will not delete if they have an image

### ISSUE THREAD

**Issue by RyanBriggsDev** [ytsruh/wrongmove#106]

**Comment by ytsruh** [comment]
This is annoying. I've not set up [referential actions](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions) on the model so this is causing the bug.

Easy for me to fix but I'm concnered that Prisma isnt throwing an error back to the API so will have to see how I can handle this case if it happens.

Either way I'll have this fixed today or tomororw
