### ISSUE TITLE
Add option for user query when calling all sales listing data

### ISSUE THREAD

**Issue by RyanBriggsDev** [ytsruh/wrongmove#113]
Need to amend backend code for /sales route so public users can filter data for the following

- Min/Max price
- Number of bedrooms
- Property Type

**Comment by ytsruh** [comment]
Combining multiple queries together could be tricky. Help links:
https://github.com/prisma/prisma/discussions/8216
https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting

Probably best approach is to check for valid query string, reject if any query is not expected, create a function to build a query that can be passed to Prisma

**Comment by ytsruh** [comment]
Right this is done in the api branch. You can use the following query parameters 'minprice' 'maxprice' 'bedrooms' 'propertytype' (all are lower case)

A few notes after doing this:
1) Bedrooms returns greater than or equal to the number you input
2) min & max price work with each other or just using one
3) propertytype is a pain for reasons whiich I'll cover below. This query will work if it contains the input (it will ignore case sensitivity)

Doing the property type made me realise we've made an error with this piece of data. Neither on the client or server do we validate the user input here, you can literaly put any valid string. This makes the querying almost impossible to do reliably. In an ideal world we would use a) a select input field on the client side & b) some sort of enum value to validate before saving to database. None of this is a deal-breaker but its damn annoying
