### ISSUE TITLE
Error on sign in

### ISSUE THREAD

**Issue by RyanBriggsDev** [ytsruh/wrongmove#60]
Getting the following error on when signing in as agent... 

<img width="986" alt="Screenshot 2022-12-13 at 10 02 21" src="https://user-images.githubusercontent.com/92796110/207287760-f33de8cd-9d1c-4a77-b2a7-48266c577ac0.png">

**Comment by ytsruh** [comment]
My bad, you need the envinroment varaibles. Will send them over to you now
