### ISSUE TITLE
Agent create sales listing page doesn't redirect after successful submission

### ISSUE THREAD

**Issue by ytsruh** [ytsruh/wrongmove#69]
Should probably redirect a user back to the dashboard?

**Comment by RyanBriggsDev** [comment]
Planned to add this once we've got the for public for sale listing created. 

When listing is created by agent we can push them to the public listing?

**Comment by ytsruh** [comment]
Yup fine with this approach. Close the issue if you'll remember to do it

**Comment by ytsruh** [comment]
In my PR that adds the Agent Listing functionality I've set this to redirect to the agent dashboard - for both sales & rentals. 

Change it when you're ready to
