### ISSUE TITLE
Create 'Coming soon' page

### ISSUE THREAD

**Issue by ytsruh** [ytsruh/wrongmove#76]
Page is a catch all for the links on the homepage & others that wont have functionality built for it

**Comment by shyamtawli** [comment]
i can make it more attractive if you want?

**Comment by ytsruh** [comment]
Hi Shyam, thanks for the message. This is a project between me and a friend (@RyanBriggsDev) but happy for you to help out if you would like.

This issue is a good one. We just need a generic 'coming soon' page that we can link any broken links to.

If you would like to open a pull request and contribute that would be helpful. This is a NextJS app and we're cloning the [Rightmove](https://www.rightmove.co.uk/) website.

Also : Please create your branch from the dev branch. The master branch is not upto date

**Comment by shyamtawli** [comment]
Okay i will see if i can make it or not.

**Comment by ytsruh** [comment]
Hey @shyamtawli ..... are you working on this? any idea when you will be done?

**Comment by shyamtawli** [comment]
@ytsruh i can create a page if you want but i dont know where to attach it.

**Comment by ytsruh** [comment]
No problems, we'll get one built today or tomorrow. 

We're working in the dev branch for now. Its a NextJs project so a page like this one can just go into the root of the 'pages' directoty

**Comment by shyamtawli** [comment]
i dont have experience in nextjs.
i work in reactjs

**Comment by ytsruh** [comment]
NextJS is just a framework for React. All React code will work inside it.

**Comment by shyamtawli** [comment]
i will learn it after reactjs.
